---
name: Main

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        function-dir: [ lambda ]

    uses: andreswebs/gh-actions/.github/workflows/ecr-publish-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: ${{ vars.AWS_ECR_REPO_NAME }}
      context-dir: ./${{ matrix.function-dir }}
      matrix-step-name: build
      matrix-key: ${{ matrix.function-dir }}

  images-tfvars:
    needs: [ build ]
    uses: andreswebs/gh-actions/.github/workflows/images-tfvars.yml@main
    with:
      runs-on: ubuntu-latest
      matrix-step-name: build

