---
name: Main

permissions:
  id-token: write
  contents: read
  security-events: write

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".github/**"

  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - ".github/**"

jobs:
  build:
    strategy:
      matrix:
        function:
          - name: sns-to-telegram
            dir: ./lambda

    uses: andreswebs/gh-actions/.github/workflows/aws-ecr-push-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: ${{ vars.AWS_ECR_REPO_NAMESPACE }}/${{ matrix.function.name }}
      context-dir: ${{ matrix.function.dir }}
      image-artifact: image-${{ matrix.function.name }}
      matrix-step-name: build
      matrix-key: ${{ matrix.function.name }}

  images-tfvars:
    needs: [build]
    uses: andreswebs/gh-actions/.github/workflows/images-tfvars.yml@main
    with:
      runs-on: ubuntu-latest
      matrix-step-name: build

  ## workaround for issue:
  # https://github.com/orgs/community/discussions/26671
  vars-dev:
    needs: [images-tfvars]
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      workdir: ${{ vars.WORKDIR }}
      backend-key: ${{ vars.BACKEND_KEY }}
      ssm-param-telegram-bot-token: ${{ vars.SSM_PARAM_TELEGRAM_BOT_TOKEN }}
      ssm-param-telegram-chat-id: ${{ vars.SSM_PARAM_TELEGRAM_CHAT_ID }}
    steps:
      - run: echo

  tfbackend-dev:
    needs: [images-tfvars, vars-dev]
    uses: andreswebs/gh-actions/.github/workflows/tfbackend.yml@main
    with:
      runs-on: ubuntu-latest
      environment: dev
      bucket: ${{ vars.BACKEND_BUCKET }}
      table: ${{ vars.BACKEND_TABLE }}
      key: ${{ needs.vars-dev.outputs.backend-key }}
      region: ${{ vars.AWS_REGION }}
      tfbackend: dev.s3.tfbackend

  tfvars-dev:
    needs: [vars-dev]
    uses: ./.github/workflows/tfvars.yml
    with:
      runs-on: ubuntu-latest
      ssm-param-telegram-bot-token: ${{ needs.vars-dev.outputs.ssm-param-telegram-bot-token }}
      ssm-param-telegram-chat-id: ${{ needs.vars-dev.outputs.ssm-param-telegram-chat-id }}

  tf-plan-dev:
    name: TF Plan - dev
    needs: [images-tfvars, tfbackend-dev, vars-dev, tfvars-dev]
    uses: andreswebs/gh-actions/.github/workflows/tf-plan.yml@main
    with:
      runs-on: ubuntu-latest
      environment: dev
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      working-directory: ${{ needs.vars-dev.outputs.workdir }}
      tfbackend: ${{ needs.tfbackend-dev.outputs.tfbackend }}
      tfbackend-is-artifact: true
      images-tfvars: ${{ needs.images-tfvars.outputs.tfvars }}
      tfvars: ${{ needs.tfvars-dev.outputs.tfvars }}
      tfplan: dev.tfplan

  images-tag-dev:
    needs: [tf-plan-dev]
    uses: andreswebs/gh-actions/.github/workflows/images-env-tags.yml@main
    with:
      runs-on: ubuntu-latest
      environment: dev
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}

  tf-apply-dev:
    name: TF Apply - dev
    needs: [tfbackend-dev, vars-dev, tf-plan-dev, images-tag-dev]
    uses: andreswebs/gh-actions/.github/workflows/tf-apply.yml@main
    with:
      runs-on: ubuntu-latest
      environment: dev
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      working-directory: ${{ needs.vars-dev.outputs.workdir }}
      tfbackend: ${{ needs.tfbackend-dev.outputs.tfbackend }}
      tfbackend-is-artifact: true
      tfplan: ${{ needs.tf-plan-dev.outputs.tfplan }}
