---
name: Main

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - ./.github/dependabot.yml

  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - ./.github/dependabot.yml

jobs:

  build:
    strategy:
      matrix:
        function-dir: [ lambda ]

    uses: andreswebs/gh-actions/.github/workflows/ecr-publish-image.yml@main
    with:
      runs-on: ubuntu-latest
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      ecr-repo-name: ${{ vars.AWS_ECR_REPO_NAME }}
      context-dir: ./${{ matrix.function-dir }}
      matrix-step-name: build
      matrix-key: ${{ matrix.function-dir }}

  images-tfvars:
    needs: [ build ]
    name: Images TF vars
    uses: andreswebs/gh-actions/.github/workflows/images-tfvars.yml@main
    with:
      runs-on: ubuntu-latest
      matrix-step-name: build

  ## workaround for issue:
  # https://github.com/orgs/community/discussions/26671
  vars-dev:
    needs: [ build, images-tfvars ]
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      backend-key: ${{ vars.BACKEND_KEY }}
      ssm-param-telegram-bot-token: ${{ vars.SSM_PARAM_TELEGRAM_BOT_TOKEN }}
      ssm-param-telegram-chat-id: ${{ vars.SSM_PARAM_TELEGRAM_CHAT_ID }}
    steps:
      - run: echo

  tfbackend-dev:
    needs: [ build, images-tfvars ]
    name: TF Backend - dev
    uses: andreswebs/gh-actions/.github/workflows/tfbackend.yml@main
    with:
      runs-on: ubuntu-latest
      environment: dev
      bucket: ${{ vars.BACKEND_BUCKET }}
      table: ${{ vars.BACKEND_TABLE }}
      key: ${{ needs.vars-dev.outputs.backend-key }}
      region: ${{ vars.AWS_REGION }}
      tfbackend: dev.s3.tfbackend

  tfvars-dev:
    needs: [ vars-dev ]
    uses: ./.github/workflows/tfvars.yml
    with:
      runs-on: ubuntu-latest
      ssm-param-telegram-bot-token: ${{ needs.vars-dev.outputs.ssm-param-telegram-bot-token }}
      ssm-param-telegram-chat-id: ${{ needs.vars-dev.outputs.ssm-param-telegram-chat-id }}

  tf-plan-dev:
    name: TF Plan - dev
    needs: [ tfbackend-dev, tfvars-dev ]
    uses: andreswebs/gh-actions/.github/workflows/tf-plan.yml@main
    with:
      runs-on: ununtu-latest
      environment: dev
      working-directory: ${{ vars.WORKDIR }}
      aws-region: ${{ vars.AWS_REGION }}
      role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      tfbackend: ${{ needs.tfbackend-dev.outputs.tfbackend }}
      tfbackend-is-artifact: true
      images-tfvars: ${{ needs.images-tfvars.outputs.tfvars }}
      tfvars: ${{ needs.tfvars-dev.outputs.tfvars }}
      tfplan: dev.tfplan

  # images-tag-dev:
  #   needs: [ build, images-tfvars ]
  #   uses: andreswebs/gh-actions/.github/workflows/images-env-tags.yml@main
  #   environment: dev
  #   role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
